robots_extra_rules: |
  Disallow: /interprets
  Disallow: /albums
  Disallow: /songs
  Disallow: /places
  Disallow: /index.php/interprets
  Disallow: /index.php/albums
  Disallow: /index.php/songs
  Disallow: /index.php/places

fail2ban_extra_filters: |
  [apache-facets]
  enabled  = true
  port     = http,https
  filter   = apache-facets
  logpath  = /var/log/apache2/islandora-access.log
  maxretry = 35
  findtime = 300
  bantime = 2m
  bantime.increment = true

fail2ban_failregex: "(interprets|albums|songs|places)"
