---
- name: Prepare ssh keys destination dir
  ansible.builtin.file:
    path: '{{ github_ssh_keys_dir }}'
    state: directory
    owner: islandora
    group: islandora
    mode: '555'

- name: Copy github ssh keys
  ansible.builtin.copy:
    src: 'key.{{ item.name }}'
    dest: '{{ github_ssh_keys_dir }}/key.{{ item.name }}'
    owner: islandora
    group: islandora
    mode: '400'
  loop: '{{ islandora_developers }}'

- name: Set up git commit aliases
  community.general.git_config:
    name: 'alias.commit-{{ item.name }}'
    scope: global
    value: '-c user.email="{{ item.github_email }}" -c user.name="{{ item.github_name }}" commit'
  loop: '{{ islandora_developers }}'
  become: yes
  become_user: islandora

- name: Set up git push aliases
  community.general.git_config:
    name: 'alias.push-{{ item.name }}'
    scope: global
    value: '-c core.sshCommand="ssh -i {{ github_ssh_keys_dir }}/key.{{ item.name }}" push'
  loop: '{{ islandora_developers }}'
  become: yes
  become_user: islandora

- name: Set up git pull aliases
  community.general.git_config:
    name: 'alias.pull-{{ item.name }}'
    scope: global
    value: '-c core.sshCommand="ssh -i {{ github_ssh_keys_dir }}/key.{{ item.name }}" pull'
  loop: '{{ islandora_developers }}'
  become: yes
  become_user: islandora

- name: Set up git clone aliases
  community.general.git_config:
    name: 'alias.clone-{{ item.name }}'
    scope: global
    value: '-c core.sshCommand="ssh -i {{ github_ssh_keys_dir }}/key.{{ item.name }}" clone'
  loop: '{{ islandora_developers }}'
  become: yes
  become_user: islandora


