---
- name: Copy .vimrc to user's home directory
  ansible.builtin.copy:
    src: .vimrc 
    dest: "/home/{{ username }}/.vimrc"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'
  become: yes
  become_user: islandora

- name: Set alias to switch to drupal directory
  ansible.builtin.lineinfile:
    path: "/home/{{ username }}/.bashrc"
    line: "alias cddrupal='cd {{ drupal_dir }}'"
    create: yes
  become_user: islandora

- name: Set alias to switch to drupal islandora_muni theme directory
  ansible.builtin.lineinfile:
    path: "/home/{{ username }}/.bashrc"
    line: "alias cdtheme='cd {{ drupal_dir }}/web/themes/islandora_muni'"
    create: yes
  become_user: islandora

- name: Set PATH to handle proper drush binary
  ansible.builtin.lineinfile:
    path: "/home/{{ username }}/.bashrc"
    line: "export PATH={{ drush_dir }}:$PATH"
    create: yes
  become_user: islandora

