---
- name: Islandora copy OAI hacks
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ islandora_drupal_root }}"
    mode: "{{ islandora_hacks_mode }}"
    owner: "{{ islandora_user }}"
    group: "{{ islandora_group }}"
  loop: 
    - web/modules/contrib/metatag/src/MetatagToken.php 
    - web/modules/contrib/metatag/src/Plugin/metatag/Tag/MetaNameBase.php
  tags: oai_hacks

    #- name: Debug test
    #ansible.builtin.debug: 
    #msg: "test" 
    #tags: debug

