---
- name: Islandora copy OAI hacks
  ansible.builtin.copy:
    src: "{{ item.path }}/{{ item.file }}"
    dest: "{{ islandora_drupal_root }}/{{ item.path }}//{{ item. file }}"
    mode: "{{ islandora_hacks_mode }}"
    owner: "{{ islandora_user }}"
    group: "{{ islandora_group }}"
  loop: 
    - path: "web/modules/contrib/metatag/src"
      file: "MetatagToken.php" 
    - path: "web/modules/contrib/metatag/src/Plugin/metatag/Tag"
      file: "MetaNameBase.php"
  tags: oai_hacks

    #- name: Debug test
    #ansible.builtin.debug: 
    #msg: "test" 
    #tags: debug

