---

- name: Create bin dir
  ansible.builtin.file:
    path: "{{ root_bin_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0700"
  tags: 
    - scripts
    - crontab

- name: Check bin dir
  ansible.builtin.stat:
    path: "{{ root_bin_dir }}"
  register: root_bin_dir_res
  tags: 
    - scripts
    - crontab

- name: Create bin logs
  ansible.builtin.file:
    path: "{{ root_logs_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0700"
  tags: 
    - scripts
    - crontab

- name: Check logs dir
  ansible.builtin.stat:
    path: "{{ root_logs_dir }}"
  register: root_logs_dir_res
  tags: 
    - scripts
    - crontab

- name: Copy watch script
  ansible.builtin.template:
    src: watch.sh.j2
    dest: "{{ root_bin_dir}}/watch.sh"
    owner: root
    group: root
    mode: u=rwx,g=r,o=r
  register: copy_watch_script_res
  when: 
    - root_bin_dir_res.stat.exists 
    - root_bin_dir_res.stat.isdir 
    - root_logs_dir_res.stat.exists
    - root_logs_dir_res.stat.isdir
  tags:
    - crontab
    - scripts

- name: Update cron to run watch.sh script
  ansible.builtin.cron:
    minute: "*/5"
    user: root
    name: "islandora_service_watch"
    job: "{{ root_bin_dir }}/watch.sh"
  when: copy_watch_script_res and production is defined
  tags: crontab

- name: Copy root bin scripts
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ root_bin_dir}}/{{ item }}"
    owner: root
    group: root
    mode: u=rwx,g=r,o=r
  loop:
    - bacula_backup_report.sh
    - islandora_backup_cleanup.sh
    - islandora_backup.sh
  when: 
    - root_bin_dir_res.stat.exists 
    - root_bin_dir_res.stat.isdir 
  tags: 
    - scripts
    - crontab

- name: Islandora set up backup cron job
  ansible.builtin.cron:
    minute: 0
    hour: 1
    user: root
    name: "islandora_backup"
    job: "{{ root_bin_dir}}/islandora_backup.sh"
  tags: crontab

- name: Islandora set up backup clean cron job
  ansible.builtin.cron:
    minute: 0
    hour: 4
    user: root
    name: "islandora_backup_cleanup"
    job: "{{ root_bin_dir}}/islandora_backup_cleanup.sh"
  tags: crontab

- name: Check for /etc/bacula dir
  ansible.builtin.stat:
    path: "/etc/bacula"
  register: etc_bacula_dir_res
  tags: crontab
 
- name: Islandora set up bacula report cron job
  ansible.builtin.cron:
    minute: 40
    hour: 8
    user: root
    name: "bacula_report"
    job: "{{ root_bin_dir}}/bacula_backup_report.sh"
  when: etc_bacula_dir_res.stat.exists and production is defined
  tags: crontab

- name: Create islandora bin dir
  ansible.builtin.file:
    path: "{{ islandora_bin_dir }}"
    state: directory
    owner: islandora
    group: islandora
    mode: "0700"
  tags: scripts

- name: Check islandora bin dir
  ansible.builtin.stat:
    path: "{{ islandora_bin_dir }}"
  register: islandora_bin_dir_res
  tags: scripts

- name: Copy islandora bin scripts
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ islandora_bin_dir}}/{{ item }}"
    owner: islandora
    group: islandora
    mode: u=rwx,g=r,o=r
  when: 
    - islandora_bin_dir_res.stat.exists 
    - islandora_bin_dir_res.stat.isdir 
  loop: 
    - islandora_security_checks.sh
    - islandora_drupal_security_setup.sh
  tags: scripts

- name: Check islandora_security_checks.sh script
  ansible.builtin.stat:
    path: "{{ islandora_bin_dir }}/islandora_security_checks.sh"
  register: islandora_security_checks_script_res
  tags: 
    - scripts
    - crontab
 
- name: Update cron to run islandora_security_checks.sh script
  ansible.builtin.cron:
    minute: "0"
    hour: "2"
    user: islandora
    name: "security_checks"
    job: "{{ islandora_bin_dir }}/islandora_security_checks.sh"
  when: islandora_security_checks_script_res
  become: yes
  become_user: islandora
  tags: 
    - scripts
    - crontab

- name: Add cache cleanup to cron for islandora
  ansible.builtin.cron:
    minute: "15"
    hour: "3"
    user: islandora
    name: "cache_cleanup"
    job: "/var/www/html/drupal/vendor/drush/drush/drush --root=/var/www/html/drupal cr"
  become: yes
  become_user: islandora
  tags: crontab


