---
- name: "Check if Apache is installed"
  ansible.builtin.package_facts:
    manager: "auto"
  tags: islandora_apache

- name: Copy admin IPs 
  ansible.builtin.template:
    src: adminIPs.conf.j2
    dest: /etc/apache2/adminIPs.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  when: 
    - inventory_hostname in groups["islandora"]
    - production is defined
    - "'apache2' in ansible_facts.packages"
  notify:
    - Reload apache
  tags: islandora_apache

- name: Disable status module
  ansible.builtin.command:
    cmd: a2dismod status
  when:
    - "'apache2' in ansible_facts.packages"
  notify:
    - Restart apache
  tags: islandora_apache

- name: Check if ssl site is enabled
  ansible.builtin.file:
    path: "/etc/apache2/sites-available/islandora-le-ssl.conf"
  register: le_ssl_site
  tags: islandora_apache

- name: Insert admin IPs block check
  ansible.builtin.blockinfile:
    path: "/etc/apache2/sites-available/islandora-le-ssl.conf"
    insertafter: '.*</Directory>'
    marker: "# {mark} ANSIBLE BLOCK adminIPs"
    block: |
      <Location /admin>
        Deny from all  
        Include /etc/apache2/adminIPs.conf
      </Location>
  when:
    - inventory_hostname in groups["islandora"]
    - production is defined
    - "'apache2' in ansible_facts.packages"
  tags: islandora_apache

- name: Enable rewrite module
  ansible.builtin.command:
    cmd: a2enmod rewrite
  when:
    - "'apache2' in ansible_facts.packages"
  notify:
    - Restart apache
  tags: islandora_apache

- name: Copy language switch config
  ansible.builtin.template:
    src: islandora-language-hack.conf.j2
    dest: /etc/apache2/islandora-language-hack.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  when: 
    - inventory_hostname in groups["islandora"]
    - "'apache2' in ansible_facts.packages"
  notify:
    - Reload apache
  tags: islandora_apache

- name: Check the language switch config is present
  ansible.builtin.stat:
    path: /etc/apache2/islandora-language-hack.conf
  register: language_conf
  tags: islandora_apache

- name: Insert rewrite language block
  ansible.builtin.blockinfile:
    path: "/etc/apache2/sites-available/islandora-le-ssl.conf"
    insertbefore: 'Include /etc/letsencrypt/options-ssl-apache.conf'
    marker: "# {mark} ANSIBLE BLOCK language"
    block: |
      # Language switch islandora hack
      Include /etc/apache2/islandora-language-hack.conf
  when: 
    - language_conf.stat.exists
    - inventory_hostname in groups["islandora"]
    - "'apache2' in ansible_facts.packages"
  tags: islandora_apache

- name: Copy logging config
  ansible.builtin.template:
    src: islandora-logging.conf.j2
    dest: /etc/apache2/islandora-logging.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  when: 
    - inventory_hostname in groups["islandora"]
    - "'apache2' in ansible_facts.packages"
  notify:
    - Reload apache
  tags: islandora_apache

- name: Check the logging config is present
  ansible.builtin.stat:
    path: /etc/apache2/islandora-logging.conf
  register: logging_conf
  tags: islandora_apache

- name: Insert logging block
  ansible.builtin.blockinfile:
    path: "/etc/apache2/sites-available/islandora-le-ssl.conf"
    insertbefore: 'Include /etc/letsencrypt/options-ssl-apache.conf'
    marker: "# {mark} ANSIBLE BLOCK logging"
    block: |
      # Islandora logging
      Include /etc/apache2/islandora-logging.conf
  when: 
    - logging_conf.stat.exists
    - inventory_hostname in groups["islandora"]
    - "'apache2' in ansible_facts.packages"
  tags: islandora_apache
