---
- name: Set up environment, scripts, cront etc. at Islandora servers
  hosts: islandora

  roles:
    - islandora_scripts_and_crontab
    - islandora_environment
    - islandora_git
    - islandora_apache
    - { role: islandora_fail2ban, when: production is defined and production | bool }

  tasks:
    - name: Remove islandora user privileges
      ansible.builtin.user:
        name: islandora
        password: "*"
        groups: islandora,www-data
      tags: user

    - name: Install 'simple_block' module
      community.general.composer:
        command: require
        arguments: 'drupal/simple_block'
        working_dir: "{{ drupal_dir }}"
        composer_executable: "{{ composer_bin }}"
      register: simple_block_res
      become: yes
      become_user: islandora
      tags: modules

    - name: Clear drush cache
      ansible.builtin.include_tasks: "tasks/islandora_drush_cr.yml"
      tags: modules
    
    - name: Enable 'simple_block' module
      ansible.builtin.shell:
        chdir: "{{ drupal_dir }}"
        cmd: "{{ drush_bin}} en simple_block"
      when: not simple_block_res.failed
      ignore_errors: yes
      become: yes
      become_user: islandora
      tags: modules

    - name: Install 'security_review' module
      community.general.composer:
        command: require
        arguments: 'drupal/security_review'
        working_dir: "{{ drupal_dir }}"
        composer_executable: "{{ composer_bin }}"
      register: security_review_res 
      become: yes
      become_user: islandora
      tags: modules

    - name: Clear drush cache
      ansible.builtin.include_tasks: "tasks/islandora_drush_cr.yml"
      tags: modules
 
    - name: Enable 'security_review' module
      ansible.builtin.shell:
        chdir: "{{ drupal_dir }}"
        cmd: "{{ drush_bin}} en security_review"
      when: not security_review_res.failed
      ignore_errors: yes
      become: yes
      become_user: islandora
      tags: modules

    - name: Install 'flood_control' module
      community.general.composer:
        command: require
        arguments: 'drupal/flood_control'
        working_dir: "{{ drupal_dir }}"
        composer_executable: "{{ composer_bin }}"
      register: flood_control_res
      become: yes
      become_user: islandora
      tags: modules
    
    - name: Clear drush cache
      ansible.builtin.include_tasks: "tasks/islandora_drush_cr.yml"
      tags: modules
 
    - name: Enable 'flood_control' module
      ansible.builtin.shell:
        chdir: "{{ drupal_dir }}"
        cmd: "{{ drush_bin}} en flood_control"
      when: not flood_control_res.failed
      ignore_errors: yes
      become: yes
      become_user: islandora
      tags: modules

    - name: Configure ip_limit for 'flood_control' module
      ansible.builtin.shell:
        chdir: "{{ drupal_dir }}"
        cmd: "{{ drush_bin}} -y cset user.flood ip_limit 3"
      when: not flood_control_res.failed
      become: yes
      become_user: islandora
      tags: modules

    - name: Configure user_limit for 'flood_control' module
      ansible.builtin.shell:
        chdir: "{{ drupal_dir }}"
        cmd: "{{ drush_bin}} -y cset user.flood user_limit 3"
      when: not flood_control_res.failed
      become: yes
      become_user: islandora
      tags: modules

    - name: Configure user.settings register admin_only for 'flood_control' module
      ansible.builtin.shell:
        chdir: "{{ drupal_dir }}"
        cmd: "{{ drush_bin}} -y cset user.settings register admin_only"
      when: not flood_control_res.failed
      become: yes
      become_user: islandora
      tags: modules

    - name: Install 'openid_connect' module
      community.general.composer:
        command: require
        arguments: 'drupal/openid_connect:^3.0@alpha'
        working_dir: "{{ drupal_dir }}"
        composer_executable: "{{ composer_bin }}"
      register: openid_connect_block_res
      become: yes
      become_user: islandora
      tags: 
        - modules
        - openid_connect
     
    - name: Clear drush cache
      ansible.builtin.include_tasks: "tasks/islandora_drush_cr.yml"
      tags: 
        - modules
        - openid_connect
    
    - name: Install 'redirect' module
      community.general.composer:
        command: require
        arguments: 'drupal/redirect:^1.13'
        working_dir: "{{ drupal_dir }}"
        composer_executable: "{{ composer_bin }}"
      register: redirect_block_res
      become: yes
      become_user: islandora
      tags: 
        - modules
        - redirect
        
    - name: Clear drush cache
      ansible.builtin.include_tasks: "tasks/islandora_drush_cr.yml"
      tags: 
        - modules
        - redirect
 
    - name: Enable 'redirect' module
      ansible.builtin.shell:
        chdir: "{{ drupal_dir }}"
        cmd: "{{ drush_bin}} en redirect"
      when: not redirect_block_res.failed
      ignore_errors: yes
      become: yes
      become_user: islandora
      tags: 
        - modules
        - redirect

    - name: Clear drush cache
      ansible.builtin.include_tasks: "tasks/islandora_drush_cr.yml"
      tags: 
        - modules
        - redirect

    - name: Configure register module
      ansible.builtin.shell:
        chdir: "{{ drupal_dir }}"
        cmd: "{{ drush_bin}} -y config:set redirect.settings route_normalizer_enabled 1"
      when: not redirect_block_res.failed
      become: yes
      become_user: islandora
      tags: 
        - modules
        - redirect



    - name: Clear drush cache
      ansible.builtin.include_tasks: "tasks/islandora_drush_cr.yml"
      tags: 
        - modules
        - cache_clear
 
