---
- name: Islandora crontab cleanup
  hosts: islandora

  tasks:
    - name: Remove all cron entries for root
      ansible.builtin.shell: crontab -r        
      ignore_errors: true
    
    - name: Remove all cron entries for islandora
      ansible.builtin.shell: crontab -r        
      ignore_errors: true
      become: true
      become_user: islandora
  
