---
- name: Set up environment, scripts, cront etc. at Islandora servers
  hosts: phil_islandora

  roles:
    - islandora_scripts_and_crontab
    - islandora_environment
    - islandora_git
    - islandora_apache

  tasks:
    - name: Remove islandora user privileges
      ansible.builtin.user:
        name: islandora
        password: "*"
        groups: islandora,www-data
      tags: user

    - name: Install 'simple_block' module
      community.general.composer:
        command: require
        arguments: 'drupal/simple_block'
        working_dir: "{{ drupal_dir }}"
        composer_executable: "{{ composer_bin }}"
      register: simple_block_res
      become: yes
      become_user: islandora
      tags: modules

    - name: Enable 'simple_block' module
      ansible.builtin.shell:
        chdir: "{{ drupal_dir }}"
        cmd: "{{ drush_bin}} en simple_block"
      when: simple_block_res
      become: yes
      become_user: islandora
      tags: modules

    - name: Install 'security_review' module
      community.general.composer:
        command: require
        arguments: 'drupal/security_review'
        working_dir: "{{ drupal_dir }}"
        composer_executable: "{{ composer_bin }}"
      register: security_review_res
      become: yes
      become_user: islandora
      tags: modules

    - name: Enable 'security_review' module
      ansible.builtin.shell:
        chdir: "{{ drupal_dir }}"
        cmd: "{{ drush_bin}} en security_review"
      when: security_review_res
      become: yes
      become_user: islandora
      tags: modules

    - name: Install 'flood_control' module
      community.general.composer:
        command: require
        arguments: 'drupal/flood_control'
        working_dir: "{{ drupal_dir }}"
        composer_executable: "{{ composer_bin }}"
      register: flood_control_res
      become: yes
      become_user: islandora
      tags: modules

    - name: Enable 'flood_control' module
      ansible.builtin.shell:
        chdir: "{{ drupal_dir }}"
        cmd: "{{ drush_bin}} en flood_control"
      when: flood_control_res
      become: yes
      become_user: islandora
      tags: modules

    - name: Configure ip_limit for 'flood_control' module
      ansible.builtin.shell:
        chdir: "{{ drupal_dir }}"
        cmd: "{{ drush_bin}} -y cset user.flood ip_limit 3"
      when: flood_control_res
      become: yes
      become_user: islandora
      tags: modules

    - name: Configure user_limit for 'flood_control' module
      ansible.builtin.shell:
        chdir: "{{ drupal_dir }}"
        cmd: "{{ drush_bin}} -y cset user.flood user_limit 3"
      when: flood_control_res
      become: yes
      become_user: islandora
      tags: modules

    - name: Configure user.settings register admin_only for 'flood_control' module
      ansible.builtin.shell:
        chdir: "{{ drupal_dir }}"
        cmd: "{{ drush_bin}} -y cset user.settings register admin_only"
      when: flood_control_res
      become: yes
      become_user: islandora
      tags: modules




