---
- name: Islandora check for Drupal security updates
  hosts: islandora

  tasks:
    - name: Check for Drupal security updates
      ansible.builtin.shell:
        cmd: /usr/local/bin/drush --root=/var/www/html/drupal pm:security 
      register: security_updates_result
      changed_when: security_updates_result.rc == 3
      failed_when: security_updates_result.rc == 1 or security_updates_result.rc == 2 or security_updates_result.rc > 3
      become: yes
      become_user: islandora

        #    - name: Debug
        #ansible.builtin.debug:
        #msg: "Return code {{security_updates_available.rc}}"

