---
- name: Set up various scripts fo Islandora servers
  hosts: islandora

  roles:
    - islandora_scripts
    - islandora_files
    - islandora_git

  tasks:
    - name: Remove islandora user privileges
      ansible.builtin.user:
        name: islandora
        password: "!"
        groups: islandora,www-data
